version: '3.8'
services:
  mongodb:
    image: mongo:8
    container_name: interview-mongo
    ports:
      - "28117:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-data:
